terminos = {
    "ravlt":"lista rey auditivo verbal",
    "watba_r":"watba wat wat-ba wat_ba",
    "matrices":"matrix matrices",
    "vocabulario":"vocabulario vocab",
    "ace/ace-r":"ace addenbroke addenbroke's ace-iii",
    "ifs":"ineco frontal screening",
    "relatos":"wms lógica wechsler",
    "relatos neuropsi":"neuropsi",
    "córdoba":"cordoba denominacion denominación",
    "fluencia fonológica":"fluencia fonologica fonológica fluencias",
    "fluencia semántica":"fluencia semantica semántica fluencias",
    "dígitos adelante":"digitos dígitos adelante span directos directo",
    "dígitos atrás":"digitos dígitos atrás atras inversos indirecto",
    "ordenamiento n-l":"numeros letras números ordenamiento nyl",
    "aritmética":"aritmetica",
    "hayling test":"hayling control inhibitorio",
    "rocf":"figura compleja rey osterrieth",
    "tmt":"trail making test trails trazo",
    "dígitos-símbolo":"digitos simbolos símbolos claves",
    "búsqueda de simbolos":"busqueda simbolo simbolos",
    "wcst":"wisconsin card sorting",
    "faux pas":"pass minisea sea",
    "caras":"reconocimiento facial rostros",
    "eyes":"lectura mente ojos mind eyes",
    "voice":"voz lectura mente mind",
    }

lista_pruebas=[
    'WATBA-R', 'Matrices (IV)', 'Vocabulario (IV)', 'ACE-III',
    'IFS',"Relatos (WMS IV)","RAVLT (Tambor50)","Córdoba",
    "Fluencia Fonológica (P)","Fluencia Semántica (animales)",
    "Dígitos adelante (WAISIV)","Dígitos adelante Neuropsi",
    "Dígitos atrás (WAISIV)","Secuenciación (WAISIV)",
    "DigitosWAIS (WAISIV)","Ordenamiento N-L (WAISIII)",
    "Ordenamiento N-L (WAISIV)","Aritmética (WAISIII",
    "Aritmética (WAISIV)","Hayling Test","ROCF","TMT (escrito)",
    "Dígitos-Símbolo (WAISIV)","Búsqueda de Simbolos (WAISIV)",
    "STROOP","WCST (48)","HOTEL","TAP Go No Go","TAP WM",
    "TAP Atencion","TAP Flexibilidad","Faux Pas (Mini-SEA)",
    "Caras (Mini-SEA)","EYES (36)","VOICE (25)","TASIT",
    "WAIS-III","RAVLT (Pasto50)","EYES (24)","TMT (oral)",
    "SDMT","Taylor","RAVLT (Tambor60)",
    "ACE-R","Fluencia Fonológica (M)","Fluencia Semántica (casa)",
    "Cubos (WAISIV)","Cubos (WAISIV)","Rompecabezas (WAISIV)",
    "Información (WAISIV)","Balanzas (WAISIV)","Comprensión (WAISIV)",
    "Cancelación (WAISIV)","Figuras Incompletas (WAISIV)"]

