terminos = {
    "ravlt":"lista rey auditivo verbal",
    "watba_r":"watba wat wat-ba wat_ba",
    "matrices":"matrix matrices",
    "vocabulario":"vocabulario vocab",
    "ace/ace-r":"ace addenbroke addenbroke's ace-iii",
    "ifs":"ineco frontal screening",
    "relatos":"wms lógica wechsler",
    "relatos neuropsi":"neuropsi",
    "córdoba":"cordoba denominacion denominación",
    "fluencia fonológica":"fluencia fonologica fonológica fluencias",
    "fluencia semántica":"fluencia semantica semántica fluencias",
    "dígitos adelante":"digitos dígitos adelante span directos directo",
    "dígitos atrás":"digitos dígitos atrás atras inversos indirecto",
    "ordenamiento n-l":"numeros letras números ordenamiento nyl",
    "aritmética":"aritmetica",
    "hayling test":"hayling control inhibitorio",
    "rocf":"figura compleja rey osterrieth",
    "tmt":"trail making test trails trazo",
    "dígitos-símbolo":"digitos simbolos símbolos claves",
    "búsqueda de simbolos":"busqueda simbolo simbolos",
    "wcst":"wisconsin card sorting",
    "faux pas":"pass minisea sea",
    "caras":"reconocimiento facial rostros",
    "eyes":"lectura mente ojos mind eyes",
    "voice":"voz lectura mente mind",
    }

lista_pruebas=['WATBA_R', 'Matrices', 'Vocabulario', 'ACE/ACE-R', 'IFS', 'Relatos', 'Relatos Neuropsi', 'RAVLT', 'Córdoba', 'Token', 'Fluencia Fonológica', 'Fluencia Semántica', 'Dígitos adelante', 'Dígitos adelante Neuropsi', 'Dígitos atrás', 'DigitosWAIS', 'Ordenamiento N-L', 'Aritmética', 'Hayling Test', 'ROCF', 'TMT', 'Dígitos-Símbolo', 'Búsqueda de Simbolos', 'STROOP', 'WCST', 'HOTEL', 'TAP', 'Faux Pas', 'Caras', 'EYES', 'VOICE', 'TASIT', 'WAIS']

